In [1]:
# confirm in our virtual environment
import sys
print(sys.executable)

/Users/hussaintaheri/Desktop/sports-win-predictor/venv/bin/python

In [2]:
import os 
print(os.getcwd())

/Users/hussaintaheri/Desktop/sports-win-predictor/notebooks

In [3]:
import pandas as pd
df = pd.read_csv("../data/nba_pbp_2020_2025.csv")
df.head()

,Unnamed: 0.1,Unnamed: 0,gameId,actionNumber,clock,period,teamId,teamTricode,personId,playerName,...,scoreHome,scoreAway,pointsTotal,location,description,actionType,subType,videoAvailable,shotValue,actionId
0,0,0,22401186,2,PT12M00.00S,1,0,NaN,0,NaN,...,0.0,0.0,0,NaN,Start of 1st Period (1:12 PM EST),period,start,0,0,1
1,1,1,22401186,4,PT12M00.00S,1,1610612737,ATL,1631230,Barlow,...,NaN,NaN,0,h,Jump Ball Barlow vs. Carter Jr.: Tip to Mann,Jump Ball,NaN,1,0,2
2,2,2,22401186,7,PT11M43.00S,1,1610612737,ATL,1629611,Mann,...,NaN,NaN,0,h,MISS Mann 4' Fadeaway Jumper,Missed Shot,Fadeaway Jump Shot,1,2,3
3,3,3,22401186,8,PT11M40.00S,1,1610612753,ORL,1628976,Carter Jr.,...,NaN,NaN,0,v,Carter Jr. REBOUND (Off:0 Def:1),Rebound,Unknown,1,0,4
4,4,4,22401186,9,PT11M23.00S,1,1610612753,ORL,203484,Caldwell-Pope,...,NaN,NaN,0,v,MISS Caldwell-Pope 25' 3PT Jump Shot,Missed Shot,Jump Shot,1,3,5

In [4]:
# view columns to drop which ones we want be using for our model
df.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'gameId', 'actionNumber', 'clock',
       'period', 'teamId', 'teamTricode', 'personId', 'playerName',
       'playerNameI', 'xLegacy', 'yLegacy', 'shotDistance', 'shotResult',
       'isFieldGoal', 'scoreHome', 'scoreAway', 'pointsTotal', 'location',
       'description', 'actionType', 'subType', 'videoAvailable', 'shotValue',
       'actionId'],
      dtype='object')

In [6]:
df.isna().count()

gameId        3282178
clock         3282178
period        3282178
scoreHome     3282178
scoreAway     3282178
location      3282178
actionType    3282178
dtype: int64

In [7]:
df.head(20)

      gameId        clock  period  scoreHome  scoreAway location   actionType
0   22401186  PT12M00.00S       1        0.0        0.0      NaN       period
2   22401186  PT11M43.00S       1        NaN        NaN        h  Missed Shot
3   22401186  PT11M40.00S       1        NaN        NaN        v      Rebound
4   22401186  PT11M23.00S       1        NaN        NaN        v  Missed Shot
5   22401186  PT11M19.00S       1        NaN        NaN        h      Rebound
6   22401186  PT11M15.00S       1        2.0        0.0        h    Made Shot
7   22401186  PT10M58.00S       1        NaN        NaN        v  Missed Shot
8   22401186  PT10M55.00S       1        NaN        NaN        v      Rebound
9   22401186  PT10M49.00S       1        2.0        3.0        v    Made Shot
10  22401186  PT10M35.00S       1        NaN        NaN        h     Turnover
11  22401186  PT10M35.00S       1        NaN        NaN        v          NaN
12  22401186  PT10M31.00S       1        2.0        5.0        v    Made Shot
13  22401186  PT10M13.00S       1        NaN        NaN        h  Missed Shot
14  22401186  PT10M11.00S       1        NaN        NaN        v      Rebound
15  22401186  PT10M06.00S       1        NaN        NaN        v  Missed Shot
16  22401186  PT10M01.00S       1        NaN        NaN        v      Rebound
17  22401186  PT09M51.00S       1        NaN        NaN        v  Missed Shot
18  22401186  PT09M49.00S       1        NaN        NaN        v      Rebound
19  22401186  PT09M49.00S       1        NaN        NaN        h         Foul
20  22401186  PT09M49.00S       1        2.0        6.0        v   Free Throw

In [8]:
# fill missing values for home and away so it carries the values forward and not update whenever a score changes
# use forward fill method
df[["scoreHome","scoreAway"]] = df.groupby(["gameId"])[["scoreHome", "scoreAway"]].ffill()

In [9]:
df.head(20)

      gameId        clock  period  scoreHome  scoreAway location   actionType
0   22401186  PT12M00.00S       1        0.0        0.0      NaN       period
2   22401186  PT11M43.00S       1        0.0        0.0        h  Missed Shot
3   22401186  PT11M40.00S       1        0.0        0.0        v      Rebound
4   22401186  PT11M23.00S       1        0.0        0.0        v  Missed Shot
5   22401186  PT11M19.00S       1        0.0        0.0        h      Rebound
6   22401186  PT11M15.00S       1        2.0        0.0        h    Made Shot
7   22401186  PT10M58.00S       1        2.0        0.0        v  Missed Shot
8   22401186  PT10M55.00S       1        2.0        0.0        v      Rebound
9   22401186  PT10M49.00S       1        2.0        3.0        v    Made Shot
10  22401186  PT10M35.00S       1        2.0        3.0        h     Turnover
11  22401186  PT10M35.00S       1        2.0        3.0        v          NaN
12  22401186  PT10M31.00S       1        2.0        5.0        v    Made Shot
13  22401186  PT10M13.00S       1        2.0        5.0        h  Missed Shot
14  22401186  PT10M11.00S       1        2.0        5.0        v      Rebound
15  22401186  PT10M06.00S       1        2.0        5.0        v  Missed Shot
16  22401186  PT10M01.00S       1        2.0        5.0        v      Rebound
17  22401186  PT09M51.00S       1        2.0        5.0        v  Missed Shot
18  22401186  PT09M49.00S       1        2.0        5.0        v      Rebound
19  22401186  PT09M49.00S       1        2.0        5.0        h         Foul
20  22401186  PT09M49.00S       1        2.0        6.0        v   Free Throw

In [10]:
# get the last row of every game
temp_df = df.groupby("gameId").last().reset_index()

# create target column for both dataframes comparing to see if home team won or not
temp_df["home_team_won"] = (temp_df["scoreHome"] > temp_df["scoreAway"]).astype(int)

# now merge both dataframes so we know the target value for all rows
df = pd.merge(df, temp_df[["home_team_won", "gameId"]], on = "gameId")

In [11]:
df.head(20)

,gameId,clock,period,scoreHome,scoreAway,location,actionType,home_team_won
0,22401186,PT12M00.00S,1,0.0,0.0,NaN,period,1
1,22401186,PT11M43.00S,1,0.0,0.0,h,Missed Shot,1
2,22401186,PT11M40.00S,1,0.0,0.0,v,Rebound,1
3,22401186,PT11M23.00S,1,0.0,0.0,v,Missed Shot,1
4,22401186,PT11M19.00S,1,0.0,0.0,h,Rebound,1
5,22401186,PT11M15.00S,1,2.0,0.0,h,Made Shot,1
6,22401186,PT10M58.00S,1,2.0,0.0,v,Missed Shot,1
7,22401186,PT10M55.00S,1,2.0,0.0,v,Rebound,1
8,22401186,PT10M49.00S,1,2.0,3.0,v,Made Shot,1
9,22401186,PT10M35.00S,1,2.0,3.0,h,Turnover,1
10,22401186,PT10M35.00S,1,2.0,3.0,v,NaN,1
11,22401186,PT10M31.00S,1,2.0,5.0,v,Made Shot,1
12,22401186,PT10M13.00S,1,2.0,5.0,h,Missed Shot,1
13,22401186,PT10M11.00S,1,2.0,5.0,v,Rebound,1
14,22401186,PT10M06.00S,1,2.0,5.0,v,Missed Shot,1
15,22401186,PT10M01.00S,1,2.0,5.0,v,Rebound,1
16,22401186,PT09M51.00S,1,2.0,5.0,v,Missed Shot,1
17,22401186,PT09M49.00S,1,2.0,5.0,v,Rebound,1
18,22401186,PT09M49.00S,1,2.0,5.0,h,Foul,1
19,22401186,PT09M49.00S,1,2.0,6.0,v,Free Throw,1

In [12]:
df.tail(20)

,gameId,clock,period,scoreHome,scoreAway,location,actionType,home_team_won
3282158,22000496,PT00M06.90S,4,119.0,122.0,h,Rebound,0
3282159,22000496,PT00M06.90S,4,119.0,122.0,v,Foul,0
3282160,22000496,PT00M06.90S,4,120.0,122.0,h,Free Throw,0
3282161,22000496,PT00M06.90S,4,120.0,122.0,v,Substitution,0
3282162,22000496,PT00M06.90S,4,120.0,122.0,h,Free Throw,0
3282163,22000496,PT00M05.80S,4,120.0,122.0,v,Rebound,0
3282164,22000496,PT00M05.80S,4,120.0,122.0,h,Foul,0
3282165,22000496,PT00M05.80S,4,120.0,123.0,v,Free Throw,0
3282166,22000496,PT00M05.80S,4,120.0,123.0,h,Substitution,0
3282167,22000496,PT00M05.80S,4,120.0,124.0,v,Free Throw,0
3282168,22000496,PT00M02.90S,4,120.0,124.0,v,Foul,0
3282169,22000496,PT00M02.90S,4,121.0,124.0,h,Free Throw,0
3282170,22000496,PT00M02.90S,4,121.0,124.0,h,Free Throw,0
3282171,22000496,PT00M01.20S,4,121.0,124.0,h,Rebound,0
3282172,22000496,PT00M01.20S,4,121.0,124.0,NaN,Instant Replay,0
3282173,22000496,PT00M01.20S,4,121.0,124.0,h,Substitution,0
3282174,22000496,PT00M01.20S,4,121.0,124.0,h,Substitution,0
3282175,22000496,PT00M00.70S,4,121.0,124.0,h,Missed Shot,0
3282176,22000496,PT00M00.10S,4,121.0,124.0,h,Rebound,0
3282177,22000496,PT00M00.00S,4,121.0,124.0,NaN,period,0

In [13]:
df.dtypes

gameId             int64
clock             object
period             int64
scoreHome        float64
scoreAway        float64
location          object
actionType        object
home_team_won      int64
dtype: object

In [14]:
# check how much periods in our df
df["period"].value_counts()

period
4    832755
2    830947
3    804796
1    791902
5     19474
6      2076
7       228
Name: count, dtype: int64

In [15]:
df.head()

,gameId,clock,period,scoreHome,scoreAway,location,actionType,home_team_won
0,22401186,PT12M00.00S,1,0.0,0.0,NaN,period,1
1,22401186,PT11M43.00S,1,0.0,0.0,h,Missed Shot,1
2,22401186,PT11M40.00S,1,0.0,0.0,v,Rebound,1
3,22401186,PT11M23.00S,1,0.0,0.0,v,Missed Shot,1
4,22401186,PT11M19.00S,1,0.0,0.0,h,Rebound,1

In [16]:
# created a function to convert clock and period columns to a single column of just seconds
def parse_clock(clock, period):
    clock = clock.split("M")
    clock[0] = clock[0][2:]
    clock[1] = clock[1][:-4]

    clock_seconds_left = int(clock[0]) * 60 + int(clock[1])

    if period < 5:
        seconds_before_period = (period - 1) * 720
        seconds = seconds_before_period + (720 - clock_seconds_left)
    else:
        seconds_before_period = 2880 + (period - 5) * 300
        seconds = seconds_before_period + (300 - clock_seconds_left)

    return seconds

In [17]:
# apply the function to the data frame
df["seconds"] = df.apply(lambda row: parse_clock(row["clock"], row["period"]), axis = 1)
df.head(20)

,gameId,clock,period,scoreHome,scoreAway,location,actionType,home_team_won,seconds
0,22401186,PT12M00.00S,1,0.0,0.0,NaN,period,1,0
1,22401186,PT11M43.00S,1,0.0,0.0,h,Missed Shot,1,17
2,22401186,PT11M40.00S,1,0.0,0.0,v,Rebound,1,20
3,22401186,PT11M23.00S,1,0.0,0.0,v,Missed Shot,1,37
4,22401186,PT11M19.00S,1,0.0,0.0,h,Rebound,1,41
5,22401186,PT11M15.00S,1,2.0,0.0,h,Made Shot,1,45
6,22401186,PT10M58.00S,1,2.0,0.0,v,Missed Shot,1,62
7,22401186,PT10M55.00S,1,2.0,0.0,v,Rebound,1,65
8,22401186,PT10M49.00S,1,2.0,3.0,v,Made Shot,1,71
9,22401186,PT10M35.00S,1,2.0,3.0,h,Turnover,1,85
10,22401186,PT10M35.00S,1,2.0,3.0,v,NaN,1,85
11,22401186,PT10M31.00S,1,2.0,5.0,v,Made Shot,1,89
12,22401186,PT10M13.00S,1,2.0,5.0,h,Missed Shot,1,107
13,22401186,PT10M11.00S,1,2.0,5.0,v,Rebound,1,109
14,22401186,PT10M06.00S,1,2.0,5.0,v,Missed Shot,1,114
15,22401186,PT10M01.00S,1,2.0,5.0,v,Rebound,1,119
16,22401186,PT09M51.00S,1,2.0,5.0,v,Missed Shot,1,129
17,22401186,PT09M49.00S,1,2.0,5.0,v,Rebound,1,131
18,22401186,PT09M49.00S,1,2.0,5.0,h,Foul,1,131
19,22401186,PT09M49.00S,1,2.0,6.0,v,Free Throw,1,131

In [18]:
df.tail(20)

,gameId,clock,period,scoreHome,scoreAway,location,actionType,home_team_won,seconds
3282158,22000496,PT00M06.90S,4,119.0,122.0,h,Rebound,0,2874
3282159,22000496,PT00M06.90S,4,119.0,122.0,v,Foul,0,2874
3282160,22000496,PT00M06.90S,4,120.0,122.0,h,Free Throw,0,2874
3282161,22000496,PT00M06.90S,4,120.0,122.0,v,Substitution,0,2874
3282162,22000496,PT00M06.90S,4,120.0,122.0,h,Free Throw,0,2874
3282163,22000496,PT00M05.80S,4,120.0,122.0,v,Rebound,0,2875
3282164,22000496,PT00M05.80S,4,120.0,122.0,h,Foul,0,2875
3282165,22000496,PT00M05.80S,4,120.0,123.0,v,Free Throw,0,2875
3282166,22000496,PT00M05.80S,4,120.0,123.0,h,Substitution,0,2875
3282167,22000496,PT00M05.80S,4,120.0,124.0,v,Free Throw,0,2875
3282168,22000496,PT00M02.90S,4,120.0,124.0,v,Foul,0,2878
3282169,22000496,PT00M02.90S,4,121.0,124.0,h,Free Throw,0,2878
3282170,22000496,PT00M02.90S,4,121.0,124.0,h,Free Throw,0,2878
3282171,22000496,PT00M01.20S,4,121.0,124.0,h,Rebound,0,2879
3282172,22000496,PT00M01.20S,4,121.0,124.0,NaN,Instant Replay,0,2879
3282173,22000496,PT00M01.20S,4,121.0,124.0,h,Substitution,0,2879
3282174,22000496,PT00M01.20S,4,121.0,124.0,h,Substitution,0,2879
3282175,22000496,PT00M00.70S,4,121.0,124.0,h,Missed Shot,0,2880
3282176,22000496,PT00M00.10S,4,121.0,124.0,h,Rebound,0,2880
3282177,22000496,PT00M00.00S,4,121.0,124.0,NaN,period,0,2880

In [19]:
# count the amount of values for seconds
df["seconds"].isna().sum()

np.int64(0)

In [20]:
# now drop the clock column
df = df.drop(["clock"], axis = 1)
df.head()

,gameId,period,scoreHome,scoreAway,location,actionType,home_team_won,seconds
0,22401186,1,0.0,0.0,NaN,period,1,0
1,22401186,1,0.0,0.0,h,Missed Shot,1,17
2,22401186,1,0.0,0.0,v,Rebound,1,20
3,22401186,1,0.0,0.0,v,Missed Shot,1,37
4,22401186,1,0.0,0.0,h,Rebound,1,41

In [21]:
df.dtypes

gameId             int64
period             int64
scoreHome        float64
scoreAway        float64
location          object
actionType        object
home_team_won      int64
seconds            int64
dtype: object

In [22]:
# check the amount of different values in actiontype
df["actionType"].value_counts()

actionType
Rebound           698025
Missed Shot       632259
Made Shot         555059
Substitution      314165
Free Throw        296706
Foul              266823
Turnover          186887
Timeout            73560
period             54470
Instant Replay     12557
Jump Ball          11786
Violation          11652
Ejection             482
Name: count, dtype: int64

In [23]:
# create 13 new columns and a 1 for what actiontype it is and the rest 0s to have our model to be able to know the importance of each type
df = pd.get_dummies(df, columns = ["actionType"], dtype = int)
df.head()

,gameId,period,scoreHome,scoreAway,location,home_team_won,seconds,actionType_Ejection,actionType_Foul,actionType_Free Throw,actionType_Instant Replay,actionType_Jump Ball,actionType_Made Shot,actionType_Missed Shot,actionType_Rebound,actionType_Substitution,actionType_Timeout,actionType_Turnover,actionType_Violation,actionType_period
0,22401186,1,0.0,0.0,NaN,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1
1,22401186,1,0.0,0.0,h,1,17,0,0,0,0,0,0,1,0,0,0,0,0,0
2,22401186,1,0.0,0.0,v,1,20,0,0,0,0,0,0,0,1,0,0,0,0,0
3,22401186,1,0.0,0.0,v,1,37,0,0,0,0,0,0,1,0,0,0,0,0,0
4,22401186,1,0.0,0.0,h,1,41,0,0,0,0,0,0,0,1,0,0,0,0,0

In [24]:
df.dtypes

gameId                         int64
period                         int64
scoreHome                    float64
scoreAway                    float64
location                      object
home_team_won                  int64
seconds                        int64
actionType_Ejection            int64
actionType_Foul                int64
actionType_Free Throw          int64
actionType_Instant Replay      int64
actionType_Jump Ball           int64
actionType_Made Shot           int64
actionType_Missed Shot         int64
actionType_Rebound             int64
actionType_Substitution        int64
actionType_Timeout             int64
actionType_Turnover            int64
actionType_Violation           int64
actionType_period              int64
dtype: object

In [25]:
df["location"].value_counts()

location
h    1616252
v    1597585
Name: count, dtype: int64

In [26]:
df["location"].isna().sum()

np.int64(68341)

In [27]:
# replace h with 2 and v with 1 and 0 for NaN values for locatin column in the df
df["location"] = df["location"].map({"h": 2, "v": 1})
df["location"] = df["location"].fillna(0)
df.head()

,gameId,period,scoreHome,scoreAway,location,home_team_won,seconds,actionType_Ejection,actionType_Foul,actionType_Free Throw,actionType_Instant Replay,actionType_Jump Ball,actionType_Made Shot,actionType_Missed Shot,actionType_Rebound,actionType_Substitution,actionType_Timeout,actionType_Turnover,actionType_Violation,actionType_period
0,22401186,1,0.0,0.0,0.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1
1,22401186,1,0.0,0.0,2.0,1,17,0,0,0,0,0,0,1,0,0,0,0,0,0
2,22401186,1,0.0,0.0,1.0,1,20,0,0,0,0,0,0,0,1,0,0,0,0,0
3,22401186,1,0.0,0.0,1.0,1,37,0,0,0,0,0,0,1,0,0,0,0,0,0
4,22401186,1,0.0,0.0,2.0,1,41,0,0,0,0,0,0,0,1,0,0,0,0,0

In [28]:
df.dtypes

gameId                         int64
period                         int64
scoreHome                    float64
scoreAway                    float64
location                     float64
home_team_won                  int64
seconds                        int64
actionType_Ejection            int64
actionType_Foul                int64
actionType_Free Throw          int64
actionType_Instant Replay      int64
actionType_Jump Ball           int64
actionType_Made Shot           int64
actionType_Missed Shot         int64
actionType_Rebound             int64
actionType_Substitution        int64
actionType_Timeout             int64
actionType_Turnover            int64
actionType_Violation           int64
actionType_period              int64
dtype: object

In [29]:
df.isna().sum()

gameId                       0
period                       0
scoreHome                    1
scoreAway                    1
location                     0
home_team_won                0
seconds                      0
actionType_Ejection          0
actionType_Foul              0
actionType_Free Throw        0
actionType_Instant Replay    0
actionType_Jump Ball         0
actionType_Made Shot         0
actionType_Missed Shot       0
actionType_Rebound           0
actionType_Substitution      0
actionType_Timeout           0
actionType_Turnover          0
actionType_Violation         0
actionType_period            0
dtype: int64

In [30]:
# check which row in the dataframe has the null values
df[df["scoreHome"].isna()]

,gameId,period,scoreHome,scoreAway,location,home_team_won,seconds,actionType_Ejection,actionType_Foul,actionType_Free Throw,actionType_Instant Replay,actionType_Jump Ball,actionType_Made Shot,actionType_Missed Shot,actionType_Rebound,actionType_Substitution,actionType_Timeout,actionType_Turnover,actionType_Violation,actionType_period
2058904,22100880,1,NaN,NaN,0.0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0

In [31]:
df[2058904:2058914]

,gameId,period,scoreHome,scoreAway,location,home_team_won,seconds,actionType_Ejection,actionType_Foul,actionType_Free Throw,actionType_Instant Replay,actionType_Jump Ball,actionType_Made Shot,actionType_Missed Shot,actionType_Rebound,actionType_Substitution,actionType_Timeout,actionType_Turnover,actionType_Violation,actionType_period
2058904,22100880,1,NaN,NaN,0.0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
2058905,22100880,1,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
2058906,22100880,1,0.0,0.0,1.0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
2058907,22100880,1,0.0,0.0,2.0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
2058908,22100880,1,0.0,0.0,2.0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
2058909,22100880,1,0.0,0.0,1.0,0,10,0,0,0,0,0,0,0,0,0,0,1,0,0
2058910,22100880,1,0.0,0.0,2.0,0,34,0,0,0,0,0,0,0,0,0,0,1,0,0
2058911,22100880,1,0.0,2.0,1.0,0,44,0,0,0,0,0,1,0,0,0,0,0,0,0
2058912,22100880,1,0.0,2.0,2.0,0,61,0,0,0,0,0,0,1,0,0,0,0,0,0
2058913,22100880,1,0.0,2.0,1.0,0,63,0,0,0,0,0,0,0,1,0,0,0,0,0

In [32]:
# drop the row to have that has null values to finally have a dataset where our model can train on
df = df.drop(2058904)

In [33]:
df.dtypes

gameId                         int64
period                         int64
scoreHome                    float64
scoreAway                    float64
location                     float64
home_team_won                  int64
seconds                        int64
actionType_Ejection            int64
actionType_Foul                int64
actionType_Free Throw          int64
actionType_Instant Replay      int64
actionType_Jump Ball           int64
actionType_Made Shot           int64
actionType_Missed Shot         int64
actionType_Rebound             int64
actionType_Substitution        int64
actionType_Timeout             int64
actionType_Turnover            int64
actionType_Violation           int64
actionType_period              int64
dtype: object

In [34]:
df.isna().sum()

gameId                       0
period                       0
scoreHome                    0
scoreAway                    0
location                     0
home_team_won                0
seconds                      0
actionType_Ejection          0
actionType_Foul              0
actionType_Free Throw        0
actionType_Instant Replay    0
actionType_Jump Ball         0
actionType_Made Shot         0
actionType_Missed Shot       0
actionType_Rebound           0
actionType_Substitution      0
actionType_Timeout           0
actionType_Turnover          0
actionType_Violation         0
actionType_period            0
dtype: int64

In [35]:
# drop the gameId since its just an identifier and our model cant learn from it
df = df.drop(columns = ["gameId"], axis = 1)

In [36]:
df.head()

,period,scoreHome,scoreAway,location,home_team_won,seconds,actionType_Ejection,actionType_Foul,actionType_Free Throw,actionType_Instant Replay,actionType_Jump Ball,actionType_Made Shot,actionType_Missed Shot,actionType_Rebound,actionType_Substitution,actionType_Timeout,actionType_Turnover,actionType_Violation,actionType_period
0,1,0.0,0.0,0.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1
1,1,0.0,0.0,2.0,1,17,0,0,0,0,0,0,1,0,0,0,0,0,0
2,1,0.0,0.0,1.0,1,20,0,0,0,0,0,0,0,1,0,0,0,0,0
3,1,0.0,0.0,1.0,1,37,0,0,0,0,0,0,1,0,0,0,0,0,0
4,1,0.0,0.0,2.0,1,41,0,0,0,0,0,0,0,1,0,0,0,0,0

In [37]:
# lets create the features and target
X = df.drop(columns = ["home_team_won"])
y = df["home_team_won"]

In [38]:
X.head()

,period,scoreHome,scoreAway,location,seconds,actionType_Ejection,actionType_Foul,actionType_Free Throw,actionType_Instant Replay,actionType_Jump Ball,actionType_Made Shot,actionType_Missed Shot,actionType_Rebound,actionType_Substitution,actionType_Timeout,actionType_Turnover,actionType_Violation,actionType_period
0,1,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
1,1,0.0,0.0,2.0,17,0,0,0,0,0,0,1,0,0,0,0,0,0
2,1,0.0,0.0,1.0,20,0,0,0,0,0,0,0,1,0,0,0,0,0
3,1,0.0,0.0,1.0,37,0,0,0,0,0,0,1,0,0,0,0,0,0
4,1,0.0,0.0,2.0,41,0,0,0,0,0,0,0,1,0,0,0,0,0

In [39]:
y.head()

0    1
1    1
2    1
3    1
4    1
Name: home_team_won, dtype: int64

In [40]:
# we found 2625533 to be the start of a new game which is really close to 80 percent of the data where we will split at
X[2625530:]

,period,scoreHome,scoreAway,location,seconds,actionType_Ejection,actionType_Foul,actionType_Free Throw,actionType_Instant Replay,actionType_Jump Ball,actionType_Made Shot,actionType_Missed Shot,actionType_Rebound,actionType_Substitution,actionType_Timeout,actionType_Turnover,actionType_Violation,actionType_period
2625531,4,102.0,110.0,1.0,2880,0,0,0,0,0,0,0,1,0,0,0,0,0
2625532,4,102.0,110.0,0.0,2880,0,0,0,0,0,0,0,0,0,0,0,0,1
2625533,1,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
2625534,1,0.0,0.0,2.0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
2625535,1,0.0,0.0,1.0,6,0,0,0,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3282173,4,121.0,124.0,2.0,2879,0,0,0,0,0,0,0,0,1,0,0,0,0
3282174,4,121.0,124.0,2.0,2879,0,0,0,0,0,0,0,0,1,0,0,0,0
3282175,4,121.0,124.0,2.0,2880,0,0,0,0,0,0,1,0,0,0,0,0,0
3282176,4,121.0,124.0,2.0,2880,0,0,0,0,0,0,0,1,0,0,0,0,0
3282177,4,121.0,124.0,0.0,2880,0,0,0,0,0,0,0,0,0,0,0,0,1

In [41]:
# since we have time series data will be creating train and test datasets manually
X_train, X_test, y_train, y_test = X.iloc[:2625532], X.iloc[2625532:], y.iloc[:2625532], y.iloc[2625532:]

In [42]:
X_train.tail()

,period,scoreHome,scoreAway,location,seconds,actionType_Ejection,actionType_Foul,actionType_Free Throw,actionType_Instant Replay,actionType_Jump Ball,actionType_Made Shot,actionType_Missed Shot,actionType_Rebound,actionType_Substitution,actionType_Timeout,actionType_Turnover,actionType_Violation,actionType_period
2625528,4,102.0,110.0,1.0,2875,0,0,0,0,0,0,0,0,0,0,0,0,0
2625529,4,102.0,110.0,2.0,2879,0,0,0,0,0,0,0,1,0,0,0,0,0
2625530,4,102.0,110.0,2.0,2880,0,0,0,0,0,0,1,0,0,0,0,0,0
2625531,4,102.0,110.0,1.0,2880,0,0,0,0,0,0,0,1,0,0,0,0,0
2625532,4,102.0,110.0,0.0,2880,0,0,0,0,0,0,0,0,0,0,0,0,1

In [43]:
X_test.head()

,period,scoreHome,scoreAway,location,seconds,actionType_Ejection,actionType_Foul,actionType_Free Throw,actionType_Instant Replay,actionType_Jump Ball,actionType_Made Shot,actionType_Missed Shot,actionType_Rebound,actionType_Substitution,actionType_Timeout,actionType_Turnover,actionType_Violation,actionType_period
2625533,1,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
2625534,1,0.0,0.0,2.0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
2625535,1,0.0,0.0,1.0,6,0,0,0,0,0,0,1,0,0,0,0,0,0
2625536,1,0.0,0.0,2.0,10,0,0,0,0,0,0,0,1,0,0,0,0,0
2625537,1,0.0,0.0,2.0,19,0,0,0,0,0,0,1,0,0,0,0,0,0

In [44]:
# check if the data is the same for train and test
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((2625532, 18), (656645, 18), (2625532,), (656645,))

In [47]:
%%time
# import the model we want to first use
from xgboost import XGBClassifier

# import the metrics we wanna use
from sklearn.metrics import log_loss, roc_auc_score, accuracy_score

# track the models we want to use on our data set
import mlflow

# start an mlflow run
with mlflow.start_run():
    
    # initialize the model and have verbosity to 1 to see the training process
    model = XGBClassifier(verbosity = 1)
    
    # train the model
    xg = model.fit(X_train, y_train)

    # log the parameters in this case the default ones
    mlflow.log_params(model.get_params())

    # log the model and give it a name
    model_info = mlflow.xgboost.log_model(xg, name = "baseline_xgboost_model1")
    
    # get the model predicted values
    y_pred = model.predict(X_test)

    # get the probabilite values, so we can use for log loss and roc_auc
    y_proba = model.predict_proba(X_test)

    # get the models metrics
    score = accuracy_score(y_test, y_pred)
    ll = log_loss(y_test, y_proba[:, 1])
    roc_auc = roc_auc_score(y_test, y_proba[:, 1])

    # log the metrics
    mlflow.log_metrics({"log_loss": ll, "accuracy_score": score, "roc_auc": roc_auc})

CPU times: user 14 s, sys: 565 ms, total: 14.5 s
Wall time: 6.05 s

In [48]:
%%time
from lightgbm import LGBMClassifier
import mlflow

with mlflow.start_run():
    
    model = LGBMClassifier(verbosity = 1)
    lgb = model.fit(X_train, y_train)
    
    mlflow.log_params(model.get_params())
    model_info = mlflow.lightgbm.log_model(lgb, name = "baseline_lightgbm_model1")
    
    y_pred = model.predict(X_test)
    y_proba = model.predict_proba(X_test)

    score = accuracy_score(y_test, y_pred)
    ll = log_loss(y_test, y_proba[:, 1])
    roc_auc = roc_auc_score(y_test, y_proba[:, 1])

    mlflow.log_metrics({"log_loss": ll, "accuracy_score": score, "roc_auc": roc_auc})

[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 1445687, number of negative: 1179845
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004691 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 607
[LightGBM] [Info] Number of data points in the train set: 2625532, number of used features: 18
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.550626 -> initscore=0.203202
[LightGBM] [Info] Start training from score 0.203202

2026/04/08 19:22:05 WARNING mlflow.lightgbm: Saving the models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

CPU times: user 15.4 s, sys: 895 ms, total: 16.3 s
Wall time: 6.28 s

In [51]:
%%time
from catboost import CatBoostClassifier
import mlflow

with mlflow.start_run():
    
    model = CatBoostClassifier()
    cb = model.fit(X_train, y_train)
    
    mlflow.log_params(model.get_params())
    model_info = mlflow.catboost.log_model(cb, name = "baseline_catboost_model1")
    
    y_pred = model.predict(X_test)
    y_proba = model.predict_proba(X_test)

    score = accuracy_score(y_test, y_pred)
    ll = log_loss(y_test, y_proba[:, 1])
    roc_auc = roc_auc_score(y_test, y_proba[:, 1])

    mlflow.log_metrics({"log_loss": ll, "accuracy_score": score, "roc_auc": roc_auc})

Learning rate set to 0.297125
0:	learn: 0.6289533	total: 255ms	remaining: 4m 14s
1:	learn: 0.5972522	total: 365ms	remaining: 3m 2s
2:	learn: 0.5760786	total: 500ms	remaining: 2m 46s
3:	learn: 0.5619212	total: 687ms	remaining: 2m 51s
4:	learn: 0.5479096	total: 818ms	remaining: 2m 42s
5:	learn: 0.5406069	total: 949ms	remaining: 2m 37s
6:	learn: 0.5321447	total: 1.13s	remaining: 2m 40s
7:	learn: 0.5264485	total: 1.3s	remaining: 2m 41s
8:	learn: 0.5220546	total: 1.43s	remaining: 2m 37s
9:	learn: 0.5182182	total: 1.53s	remaining: 2m 31s
10:	learn: 0.5149431	total: 1.67s	remaining: 2m 29s
11:	learn: 0.5127137	total: 1.79s	remaining: 2m 27s
12:	learn: 0.5100572	total: 1.98s	remaining: 2m 30s
13:	learn: 0.5075324	total: 2.09s	remaining: 2m 27s
14:	learn: 0.5062455	total: 2.28s	remaining: 2m 29s
15:	learn: 0.5045828	total: 2.41s	remaining: 2m 28s
16:	learn: 0.5034602	total: 2.58s	remaining: 2m 29s
17:	learn: 0.5027737	total: 2.7s	remaining: 2m 27s
18:	learn: 0.5014066	total: 2.86s	remaining: 2m 27s
19:	learn: 0.5003061	total: 3.06s	remaining: 2m 29s
20:	learn: 0.4999291	total: 3.21s	remaining: 2m 29s
21:	learn: 0.4992629	total: 3.35s	remaining: 2m 28s
22:	learn: 0.4985974	total: 3.46s	remaining: 2m 27s
23:	learn: 0.4977635	total: 3.57s	remaining: 2m 25s
24:	learn: 0.4974359	total: 3.7s	remaining: 2m 24s
25:	learn: 0.4969125	total: 3.82s	remaining: 2m 23s
26:	learn: 0.4966877	total: 3.92s	remaining: 2m 21s
27:	learn: 0.4963076	total: 4.09s	remaining: 2m 21s
28:	learn: 0.4960756	total: 4.24s	remaining: 2m 21s
29:	learn: 0.4958631	total: 4.39s	remaining: 2m 21s
30:	learn: 0.4952193	total: 4.5s	remaining: 2m 20s
31:	learn: 0.4951149	total: 4.61s	remaining: 2m 19s
32:	learn: 0.4944760	total: 4.75s	remaining: 2m 19s
33:	learn: 0.4940654	total: 4.86s	remaining: 2m 18s
34:	learn: 0.4938664	total: 4.97s	remaining: 2m 17s
35:	learn: 0.4936160	total: 5.09s	remaining: 2m 16s
36:	learn: 0.4933882	total: 5.19s	remaining: 2m 15s
37:	learn: 0.4932403	total: 5.33s	remaining: 2m 14s
38:	learn: 0.4927751	total: 5.45s	remaining: 2m 14s
39:	learn: 0.4926327	total: 5.54s	remaining: 2m 12s
40:	learn: 0.4923797	total: 5.62s	remaining: 2m 11s
41:	learn: 0.4923295	total: 5.71s	remaining: 2m 10s
42:	learn: 0.4921266	total: 5.79s	remaining: 2m 8s
43:	learn: 0.4920311	total: 5.88s	remaining: 2m 7s
44:	learn: 0.4919513	total: 5.99s	remaining: 2m 7s
45:	learn: 0.4916777	total: 6.11s	remaining: 2m 6s
46:	learn: 0.4915316	total: 6.22s	remaining: 2m 6s
47:	learn: 0.4914103	total: 6.38s	remaining: 2m 6s
48:	learn: 0.4912964	total: 6.48s	remaining: 2m 5s
49:	learn: 0.4911863	total: 6.62s	remaining: 2m 5s
50:	learn: 0.4910168	total: 6.75s	remaining: 2m 5s
51:	learn: 0.4907886	total: 6.88s	remaining: 2m 5s
52:	learn: 0.4907294	total: 7s	remaining: 2m 5s
53:	learn: 0.4906716	total: 7.12s	remaining: 2m 4s
54:	learn: 0.4905814	total: 7.24s	remaining: 2m 4s
55:	learn: 0.4904533	total: 7.33s	remaining: 2m 3s
56:	learn: 0.4903792	total: 7.45s	remaining: 2m 3s
57:	learn: 0.4903241	total: 7.57s	remaining: 2m 2s
58:	learn: 0.4902280	total: 7.68s	remaining: 2m 2s
59:	learn: 0.4901461	total: 7.79s	remaining: 2m 2s
60:	learn: 0.4900366	total: 7.94s	remaining: 2m 2s
61:	learn: 0.4899854	total: 8.11s	remaining: 2m 2s
62:	learn: 0.4898946	total: 8.2s	remaining: 2m 1s
63:	learn: 0.4898310	total: 8.34s	remaining: 2m 1s
64:	learn: 0.4896523	total: 8.46s	remaining: 2m 1s
65:	learn: 0.4894943	total: 8.56s	remaining: 2m 1s
66:	learn: 0.4894616	total: 8.66s	remaining: 2m
67:	learn: 0.4894110	total: 8.78s	remaining: 2m
68:	learn: 0.4893816	total: 8.92s	remaining: 2m
69:	learn: 0.4892710	total: 9.06s	remaining: 2m
70:	learn: 0.4891488	total: 9.17s	remaining: 2m
71:	learn: 0.4890558	total: 9.3s	remaining: 1m 59s
72:	learn: 0.4890016	total: 9.4s	remaining: 1m 59s
73:	learn: 0.4889042	total: 9.55s	remaining: 1m 59s
74:	learn: 0.4888116	total: 9.66s	remaining: 1m 59s
75:	learn: 0.4887592	total: 9.76s	remaining: 1m 58s
76:	learn: 0.4886872	total: 9.91s	remaining: 1m 58s
77:	learn: 0.4885837	total: 10s	remaining: 1m 58s
78:	learn: 0.4885213	total: 10.1s	remaining: 1m 57s
79:	learn: 0.4884452	total: 10.2s	remaining: 1m 57s
80:	learn: 0.4883543	total: 10.3s	remaining: 1m 56s
81:	learn: 0.4883321	total: 10.4s	remaining: 1m 56s
82:	learn: 0.4883004	total: 10.6s	remaining: 1m 56s
83:	learn: 0.4882689	total: 10.7s	remaining: 1m 56s
84:	learn: 0.4882136	total: 10.8s	remaining: 1m 56s
85:	learn: 0.4881712	total: 11s	remaining: 1m 56s
86:	learn: 0.4880905	total: 11.1s	remaining: 1m 56s
87:	learn: 0.4879849	total: 11.2s	remaining: 1m 56s
88:	learn: 0.4879227	total: 11.3s	remaining: 1m 55s
89:	learn: 0.4878661	total: 11.4s	remaining: 1m 55s
90:	learn: 0.4877825	total: 11.5s	remaining: 1m 55s
91:	learn: 0.4877622	total: 11.6s	remaining: 1m 54s
92:	learn: 0.4877148	total: 11.8s	remaining: 1m 54s
93:	learn: 0.4876930	total: 11.8s	remaining: 1m 54s
94:	learn: 0.4876508	total: 11.9s	remaining: 1m 53s
95:	learn: 0.4875767	total: 12s	remaining: 1m 53s
96:	learn: 0.4875227	total: 12.1s	remaining: 1m 52s
97:	learn: 0.4874905	total: 12.2s	remaining: 1m 52s
98:	learn: 0.4874619	total: 12.3s	remaining: 1m 51s
99:	learn: 0.4873903	total: 12.4s	remaining: 1m 51s
100:	learn: 0.4873274	total: 12.6s	remaining: 1m 52s
101:	learn: 0.4872655	total: 12.7s	remaining: 1m 51s
102:	learn: 0.4872200	total: 12.8s	remaining: 1m 51s
103:	learn: 0.4871919	total: 12.9s	remaining: 1m 51s
104:	learn: 0.4871455	total: 13.1s	remaining: 1m 51s
105:	learn: 0.4870971	total: 13.1s	remaining: 1m 50s
106:	learn: 0.4870599	total: 13.2s	remaining: 1m 50s
107:	learn: 0.4870515	total: 13.3s	remaining: 1m 49s
108:	learn: 0.4870163	total: 13.4s	remaining: 1m 49s
109:	learn: 0.4869914	total: 13.5s	remaining: 1m 49s
110:	learn: 0.4869494	total: 13.6s	remaining: 1m 48s
111:	learn: 0.4868946	total: 13.7s	remaining: 1m 48s
112:	learn: 0.4868134	total: 13.8s	remaining: 1m 48s
113:	learn: 0.4868004	total: 13.8s	remaining: 1m 47s
114:	learn: 0.4867513	total: 13.9s	remaining: 1m 47s
115:	learn: 0.4867287	total: 14s	remaining: 1m 46s
116:	learn: 0.4866971	total: 14.1s	remaining: 1m 46s
117:	learn: 0.4866702	total: 14.2s	remaining: 1m 46s
118:	learn: 0.4866214	total: 14.3s	remaining: 1m 46s
119:	learn: 0.4865725	total: 14.4s	remaining: 1m 45s
120:	learn: 0.4865038	total: 14.5s	remaining: 1m 45s
121:	learn: 0.4864770	total: 14.6s	remaining: 1m 45s
122:	learn: 0.4864268	total: 14.7s	remaining: 1m 45s
123:	learn: 0.4863849	total: 14.9s	remaining: 1m 44s
124:	learn: 0.4863531	total: 15s	remaining: 1m 44s
125:	learn: 0.4863363	total: 15.1s	remaining: 1m 44s
126:	learn: 0.4862906	total: 15.3s	remaining: 1m 44s
127:	learn: 0.4862682	total: 15.4s	remaining: 1m 44s
128:	learn: 0.4862192	total: 15.5s	remaining: 1m 44s
129:	learn: 0.4861604	total: 15.6s	remaining: 1m 44s
130:	learn: 0.4861188	total: 15.8s	remaining: 1m 44s
131:	learn: 0.4860678	total: 15.9s	remaining: 1m 44s
132:	learn: 0.4860250	total: 16s	remaining: 1m 44s
133:	learn: 0.4859727	total: 16.2s	remaining: 1m 44s
134:	learn: 0.4859170	total: 16.3s	remaining: 1m 44s
135:	learn: 0.4858910	total: 16.5s	remaining: 1m 44s
136:	learn: 0.4858665	total: 16.6s	remaining: 1m 44s
137:	learn: 0.4858168	total: 16.7s	remaining: 1m 44s
138:	learn: 0.4857931	total: 16.9s	remaining: 1m 44s
139:	learn: 0.4857346	total: 17s	remaining: 1m 44s
140:	learn: 0.4857056	total: 17.1s	remaining: 1m 44s
141:	learn: 0.4856498	total: 17.3s	remaining: 1m 44s
142:	learn: 0.4855985	total: 17.4s	remaining: 1m 44s
143:	learn: 0.4855514	total: 17.5s	remaining: 1m 43s
144:	learn: 0.4855314	total: 17.6s	remaining: 1m 43s
145:	learn: 0.4854941	total: 17.7s	remaining: 1m 43s
146:	learn: 0.4854661	total: 17.8s	remaining: 1m 43s
147:	learn: 0.4854399	total: 18s	remaining: 1m 43s
148:	learn: 0.4854232	total: 18.1s	remaining: 1m 43s
149:	learn: 0.4853941	total: 18.2s	remaining: 1m 43s
150:	learn: 0.4853434	total: 18.4s	remaining: 1m 43s
151:	learn: 0.4853177	total: 18.6s	remaining: 1m 43s
152:	learn: 0.4852808	total: 18.7s	remaining: 1m 43s
153:	learn: 0.4852244	total: 18.9s	remaining: 1m 43s
154:	learn: 0.4851970	total: 19.1s	remaining: 1m 44s
155:	learn: 0.4851856	total: 19.2s	remaining: 1m 43s
156:	learn: 0.4851388	total: 19.4s	remaining: 1m 43s
157:	learn: 0.4851009	total: 19.5s	remaining: 1m 43s
158:	learn: 0.4850564	total: 19.6s	remaining: 1m 43s
159:	learn: 0.4849984	total: 19.8s	remaining: 1m 43s
160:	learn: 0.4849707	total: 20s	remaining: 1m 44s
161:	learn: 0.4849284	total: 20.1s	remaining: 1m 44s
162:	learn: 0.4848803	total: 20.3s	remaining: 1m 43s
163:	learn: 0.4848324	total: 20.4s	remaining: 1m 43s
164:	learn: 0.4847989	total: 20.5s	remaining: 1m 43s
165:	learn: 0.4847572	total: 20.7s	remaining: 1m 43s
166:	learn: 0.4847133	total: 20.8s	remaining: 1m 43s
167:	learn: 0.4846723	total: 20.9s	remaining: 1m 43s
168:	learn: 0.4846462	total: 21s	remaining: 1m 43s
169:	learn: 0.4846279	total: 21.1s	remaining: 1m 43s
170:	learn: 0.4846074	total: 21.3s	remaining: 1m 43s
171:	learn: 0.4845517	total: 21.4s	remaining: 1m 43s
172:	learn: 0.4845182	total: 21.5s	remaining: 1m 42s
173:	learn: 0.4844954	total: 21.6s	remaining: 1m 42s
174:	learn: 0.4844460	total: 21.8s	remaining: 1m 42s
175:	learn: 0.4844214	total: 21.9s	remaining: 1m 42s
176:	learn: 0.4844066	total: 22s	remaining: 1m 42s
177:	learn: 0.4843688	total: 22.2s	remaining: 1m 42s
178:	learn: 0.4843429	total: 22.3s	remaining: 1m 42s
179:	learn: 0.4843045	total: 22.5s	remaining: 1m 42s
180:	learn: 0.4842658	total: 22.6s	remaining: 1m 42s
181:	learn: 0.4842315	total: 22.7s	remaining: 1m 42s
182:	learn: 0.4842071	total: 22.8s	remaining: 1m 41s
183:	learn: 0.4841918	total: 22.9s	remaining: 1m 41s
184:	learn: 0.4841617	total: 23s	remaining: 1m 41s
185:	learn: 0.4841336	total: 23.1s	remaining: 1m 41s
186:	learn: 0.4841134	total: 23.2s	remaining: 1m 40s
187:	learn: 0.4840881	total: 23.3s	remaining: 1m 40s
188:	learn: 0.4840590	total: 23.4s	remaining: 1m 40s
189:	learn: 0.4840383	total: 23.5s	remaining: 1m 40s
190:	learn: 0.4840184	total: 23.6s	remaining: 1m 39s
191:	learn: 0.4840074	total: 23.7s	remaining: 1m 39s
192:	learn: 0.4839679	total: 23.9s	remaining: 1m 39s
193:	learn: 0.4839301	total: 24s	remaining: 1m 39s
194:	learn: 0.4838979	total: 24.1s	remaining: 1m 39s
195:	learn: 0.4838714	total: 24.2s	remaining: 1m 39s
196:	learn: 0.4838393	total: 24.4s	remaining: 1m 39s
197:	learn: 0.4838022	total: 24.5s	remaining: 1m 39s
198:	learn: 0.4837613	total: 24.6s	remaining: 1m 39s
199:	learn: 0.4837268	total: 24.7s	remaining: 1m 38s
200:	learn: 0.4837090	total: 24.8s	remaining: 1m 38s
201:	learn: 0.4836849	total: 24.9s	remaining: 1m 38s
202:	learn: 0.4836522	total: 25.1s	remaining: 1m 38s
203:	learn: 0.4836410	total: 25.2s	remaining: 1m 38s
204:	learn: 0.4836125	total: 25.4s	remaining: 1m 38s
205:	learn: 0.4835923	total: 25.6s	remaining: 1m 38s
206:	learn: 0.4835617	total: 25.7s	remaining: 1m 38s
207:	learn: 0.4835343	total: 25.8s	remaining: 1m 38s
208:	learn: 0.4834897	total: 26s	remaining: 1m 38s
209:	learn: 0.4834550	total: 26.1s	remaining: 1m 38s
210:	learn: 0.4834310	total: 26.2s	remaining: 1m 38s
211:	learn: 0.4834027	total: 26.3s	remaining: 1m 37s
212:	learn: 0.4833666	total: 26.4s	remaining: 1m 37s
213:	learn: 0.4833456	total: 26.6s	remaining: 1m 37s
214:	learn: 0.4833192	total: 26.7s	remaining: 1m 37s
215:	learn: 0.4832846	total: 26.9s	remaining: 1m 37s
216:	learn: 0.4832592	total: 27s	remaining: 1m 37s
217:	learn: 0.4832376	total: 27.2s	remaining: 1m 37s
218:	learn: 0.4832015	total: 27.3s	remaining: 1m 37s
219:	learn: 0.4831850	total: 27.4s	remaining: 1m 37s
220:	learn: 0.4831524	total: 27.5s	remaining: 1m 37s
221:	learn: 0.4831247	total: 27.7s	remaining: 1m 37s
222:	learn: 0.4831006	total: 27.8s	remaining: 1m 36s
223:	learn: 0.4830905	total: 27.9s	remaining: 1m 36s
224:	learn: 0.4830647	total: 28.1s	remaining: 1m 36s
225:	learn: 0.4830338	total: 28.3s	remaining: 1m 36s
226:	learn: 0.4830053	total: 28.4s	remaining: 1m 36s
227:	learn: 0.4829769	total: 28.6s	remaining: 1m 36s
228:	learn: 0.4829431	total: 28.7s	remaining: 1m 36s
229:	learn: 0.4829222	total: 28.8s	remaining: 1m 36s
230:	learn: 0.4829017	total: 28.9s	remaining: 1m 36s
231:	learn: 0.4828796	total: 29s	remaining: 1m 35s
232:	learn: 0.4828568	total: 29.1s	remaining: 1m 35s
233:	learn: 0.4828486	total: 29.1s	remaining: 1m 35s
234:	learn: 0.4828203	total: 29.2s	remaining: 1m 35s
235:	learn: 0.4827898	total: 29.3s	remaining: 1m 34s
236:	learn: 0.4827584	total: 29.4s	remaining: 1m 34s
237:	learn: 0.4827441	total: 29.5s	remaining: 1m 34s
238:	learn: 0.4827172	total: 29.6s	remaining: 1m 34s
239:	learn: 0.4827052	total: 29.7s	remaining: 1m 34s
240:	learn: 0.4826790	total: 29.8s	remaining: 1m 33s
241:	learn: 0.4826524	total: 29.9s	remaining: 1m 33s
242:	learn: 0.4826316	total: 30s	remaining: 1m 33s
243:	learn: 0.4826215	total: 30.1s	remaining: 1m 33s
244:	learn: 0.4825829	total: 30.2s	remaining: 1m 33s
245:	learn: 0.4825553	total: 30.3s	remaining: 1m 32s
246:	learn: 0.4825284	total: 30.4s	remaining: 1m 32s
247:	learn: 0.4825035	total: 30.5s	remaining: 1m 32s
248:	learn: 0.4824799	total: 30.7s	remaining: 1m 32s
249:	learn: 0.4824617	total: 30.8s	remaining: 1m 32s
250:	learn: 0.4824326	total: 30.9s	remaining: 1m 32s
251:	learn: 0.4823964	total: 31.1s	remaining: 1m 32s
252:	learn: 0.4823790	total: 31.2s	remaining: 1m 32s
253:	learn: 0.4823510	total: 31.3s	remaining: 1m 31s
254:	learn: 0.4823128	total: 31.4s	remaining: 1m 31s
255:	learn: 0.4822857	total: 31.5s	remaining: 1m 31s
256:	learn: 0.4822554	total: 31.6s	remaining: 1m 31s
257:	learn: 0.4822246	total: 31.7s	remaining: 1m 31s
258:	learn: 0.4822077	total: 31.8s	remaining: 1m 31s
259:	learn: 0.4821855	total: 31.9s	remaining: 1m 30s
260:	learn: 0.4821520	total: 32s	remaining: 1m 30s
261:	learn: 0.4821323	total: 32.1s	remaining: 1m 30s
262:	learn: 0.4821152	total: 32.2s	remaining: 1m 30s
263:	learn: 0.4821012	total: 32.3s	remaining: 1m 29s
264:	learn: 0.4820710	total: 32.4s	remaining: 1m 29s
265:	learn: 0.4820422	total: 32.6s	remaining: 1m 29s
266:	learn: 0.4820204	total: 32.8s	remaining: 1m 29s
267:	learn: 0.4819901	total: 32.9s	remaining: 1m 29s
268:	learn: 0.4819591	total: 33.1s	remaining: 1m 29s
269:	learn: 0.4819333	total: 33.3s	remaining: 1m 29s
270:	learn: 0.4819158	total: 33.4s	remaining: 1m 29s
271:	learn: 0.4818884	total: 33.5s	remaining: 1m 29s
272:	learn: 0.4818613	total: 33.6s	remaining: 1m 29s
273:	learn: 0.4818461	total: 33.7s	remaining: 1m 29s
274:	learn: 0.4818368	total: 33.8s	remaining: 1m 29s
275:	learn: 0.4818177	total: 33.9s	remaining: 1m 28s
276:	learn: 0.4818109	total: 34s	remaining: 1m 28s
277:	learn: 0.4817993	total: 34.1s	remaining: 1m 28s
278:	learn: 0.4817744	total: 34.2s	remaining: 1m 28s
279:	learn: 0.4817399	total: 34.4s	remaining: 1m 28s
280:	learn: 0.4817135	total: 34.5s	remaining: 1m 28s
281:	learn: 0.4816894	total: 34.6s	remaining: 1m 28s
282:	learn: 0.4816674	total: 34.7s	remaining: 1m 28s
283:	learn: 0.4816551	total: 34.9s	remaining: 1m 28s
284:	learn: 0.4816452	total: 35s	remaining: 1m 27s
285:	learn: 0.4816143	total: 35.2s	remaining: 1m 27s
286:	learn: 0.4815833	total: 35.3s	remaining: 1m 27s
287:	learn: 0.4815656	total: 35.5s	remaining: 1m 27s
288:	learn: 0.4815470	total: 35.6s	remaining: 1m 27s
289:	learn: 0.4815127	total: 35.7s	remaining: 1m 27s
290:	learn: 0.4814948	total: 35.8s	remaining: 1m 27s
291:	learn: 0.4814692	total: 35.9s	remaining: 1m 27s
292:	learn: 0.4814359	total: 36s	remaining: 1m 26s
293:	learn: 0.4813964	total: 36.1s	remaining: 1m 26s
294:	learn: 0.4813644	total: 36.2s	remaining: 1m 26s
295:	learn: 0.4813391	total: 36.3s	remaining: 1m 26s
296:	learn: 0.4813181	total: 36.4s	remaining: 1m 26s
297:	learn: 0.4812915	total: 36.5s	remaining: 1m 26s
298:	learn: 0.4812698	total: 36.6s	remaining: 1m 25s
299:	learn: 0.4812435	total: 36.7s	remaining: 1m 25s
300:	learn: 0.4811982	total: 36.8s	remaining: 1m 25s
301:	learn: 0.4811724	total: 36.9s	remaining: 1m 25s
302:	learn: 0.4811591	total: 37s	remaining: 1m 25s
303:	learn: 0.4811272	total: 37.1s	remaining: 1m 24s
304:	learn: 0.4811122	total: 37.2s	remaining: 1m 24s
305:	learn: 0.4810809	total: 37.3s	remaining: 1m 24s
306:	learn: 0.4810625	total: 37.4s	remaining: 1m 24s
307:	learn: 0.4810336	total: 37.4s	remaining: 1m 24s
308:	learn: 0.4810183	total: 37.6s	remaining: 1m 24s
309:	learn: 0.4810073	total: 37.7s	remaining: 1m 23s
310:	learn: 0.4809844	total: 37.8s	remaining: 1m 23s
311:	learn: 0.4809621	total: 38s	remaining: 1m 23s
312:	learn: 0.4809372	total: 38.1s	remaining: 1m 23s
313:	learn: 0.4809098	total: 38.3s	remaining: 1m 23s
314:	learn: 0.4808997	total: 38.3s	remaining: 1m 23s
315:	learn: 0.4808726	total: 38.5s	remaining: 1m 23s
316:	learn: 0.4808516	total: 38.6s	remaining: 1m 23s
317:	learn: 0.4808253	total: 38.7s	remaining: 1m 23s
318:	learn: 0.4807980	total: 38.8s	remaining: 1m 22s
319:	learn: 0.4807936	total: 38.9s	remaining: 1m 22s
320:	learn: 0.4807649	total: 39s	remaining: 1m 22s
321:	learn: 0.4807357	total: 39.1s	remaining: 1m 22s
322:	learn: 0.4807109	total: 39.2s	remaining: 1m 22s
323:	learn: 0.4806851	total: 39.4s	remaining: 1m 22s
324:	learn: 0.4806720	total: 39.5s	remaining: 1m 21s
325:	learn: 0.4806473	total: 39.6s	remaining: 1m 21s
326:	learn: 0.4806278	total: 39.7s	remaining: 1m 21s
327:	learn: 0.4806084	total: 39.8s	remaining: 1m 21s
328:	learn: 0.4805889	total: 39.9s	remaining: 1m 21s
329:	learn: 0.4805812	total: 40s	remaining: 1m 21s
330:	learn: 0.4805587	total: 40.1s	remaining: 1m 21s
331:	learn: 0.4805373	total: 40.2s	remaining: 1m 20s
332:	learn: 0.4805144	total: 40.3s	remaining: 1m 20s
333:	learn: 0.4804890	total: 40.4s	remaining: 1m 20s
334:	learn: 0.4804646	total: 40.5s	remaining: 1m 20s
335:	learn: 0.4804425	total: 40.6s	remaining: 1m 20s
336:	learn: 0.4804135	total: 40.7s	remaining: 1m 20s
337:	learn: 0.4803878	total: 40.8s	remaining: 1m 19s
338:	learn: 0.4803610	total: 40.9s	remaining: 1m 19s
339:	learn: 0.4803438	total: 41s	remaining: 1m 19s
340:	learn: 0.4803178	total: 41.1s	remaining: 1m 19s
341:	learn: 0.4803017	total: 41.2s	remaining: 1m 19s
342:	learn: 0.4802666	total: 41.3s	remaining: 1m 19s
343:	learn: 0.4802413	total: 41.3s	remaining: 1m 18s
344:	learn: 0.4802152	total: 41.4s	remaining: 1m 18s
345:	learn: 0.4802020	total: 41.5s	remaining: 1m 18s
346:	learn: 0.4801812	total: 41.7s	remaining: 1m 18s
347:	learn: 0.4801644	total: 41.8s	remaining: 1m 18s
348:	learn: 0.4801466	total: 41.9s	remaining: 1m 18s
349:	learn: 0.4801285	total: 42.1s	remaining: 1m 18s
350:	learn: 0.4801127	total: 42.2s	remaining: 1m 18s
351:	learn: 0.4800879	total: 42.3s	remaining: 1m 17s
352:	learn: 0.4800559	total: 42.5s	remaining: 1m 17s
353:	learn: 0.4800440	total: 42.6s	remaining: 1m 17s
354:	learn: 0.4800266	total: 42.7s	remaining: 1m 17s
355:	learn: 0.4800036	total: 42.8s	remaining: 1m 17s
356:	learn: 0.4799921	total: 42.9s	remaining: 1m 17s
357:	learn: 0.4799744	total: 43s	remaining: 1m 17s
358:	learn: 0.4799528	total: 43.2s	remaining: 1m 17s
359:	learn: 0.4799294	total: 43.3s	remaining: 1m 17s
360:	learn: 0.4799121	total: 43.5s	remaining: 1m 16s
361:	learn: 0.4798858	total: 43.6s	remaining: 1m 16s
362:	learn: 0.4798571	total: 43.7s	remaining: 1m 16s
363:	learn: 0.4798341	total: 43.9s	remaining: 1m 16s
364:	learn: 0.4798128	total: 44s	remaining: 1m 16s
365:	learn: 0.4797903	total: 44.3s	remaining: 1m 16s
366:	learn: 0.4797787	total: 44.4s	remaining: 1m 16s
367:	learn: 0.4797609	total: 44.5s	remaining: 1m 16s
368:	learn: 0.4797297	total: 44.6s	remaining: 1m 16s
369:	learn: 0.4797247	total: 44.7s	remaining: 1m 16s
370:	learn: 0.4797049	total: 44.8s	remaining: 1m 16s
371:	learn: 0.4796896	total: 45s	remaining: 1m 15s
372:	learn: 0.4796835	total: 45.1s	remaining: 1m 15s
373:	learn: 0.4796785	total: 45.2s	remaining: 1m 15s
374:	learn: 0.4796733	total: 45.3s	remaining: 1m 15s
375:	learn: 0.4796558	total: 45.5s	remaining: 1m 15s
376:	learn: 0.4796337	total: 45.6s	remaining: 1m 15s
377:	learn: 0.4796141	total: 45.7s	remaining: 1m 15s
378:	learn: 0.4795978	total: 45.8s	remaining: 1m 15s
379:	learn: 0.4795700	total: 46s	remaining: 1m 14s
380:	learn: 0.4795359	total: 46.1s	remaining: 1m 14s

In [52]:
# now we want to choose the best hyperparameters for our model and we can automate this by using optuna which also more efficient(bayesian optimization)
import optuna
from xgboost import XGBClassifier
def objective(trial):
    # invoke suggestions of a trial object to generate hyperparameters
    max_depth = trial.suggest_int("max_depth", 3, 10)
    min_child_weight = trial.suggest_int("min_child_weight", 1, 20)
    subsample = trial.suggest_float("subsample", 0.5, 1.0)
    colsample_bytree = trial.suggest_float("colsample_bytree", 0.5, 1.0)
    learning_rate = trial.suggest_float("learning_rate", 0.01, 0.3)
    n_estimators = trial.suggest_int("n_estimators", 100, 1000)
    reg_alpha = trial.suggest_int("reg_alpha", 0, 100)
    reg_lambda = trial.suggest_int("reg_lambda", 0, 10)

    # pass those values into our model
    model = XGBClassifier(max_depth = max_depth, min_child_weight = min_child_weight, subsample = subsample, colsample_bytree = colsample_bytree,
                           learning_rate = learning_rate, n_estimators = n_estimators, reg_alpha = reg_alpha, reg_lambda = reg_lambda)
    
    model.fit(X_train, y_train)
    
    y_pred = model.predict(X_test)
    y_proba = model.predict_proba(X_test)

    # metric we want to optimize
    ll = log_loss(y_test, y_proba[:, 1])
    return ll

# since our main metric is log loss the lower score the better so our goal is to minimize it
study = optuna.create_study(direction = "minimize")

# lets use 1000 trials to find the best hyperparameters we could ever possibly find
study.optimize(objective, n_trials = 1000)

/Users/hussaintaheri/Desktop/sports-win-predictor/venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
[I 2026-04-08 21:06:19,950] A new study created in memory with name: no-name-3f4253cd-08b8-4463-95e3-af21bee5797c
[I 2026-04-08 21:06:42,542] Trial 0 finished with value: 0.4820435379044586 and parameters: {'max_depth': 6, 'min_child_weight': 18, 'subsample': 0.7710274732458069, 'colsample_bytree': 0.5057084146130187, 'learning_rate': 0.046381924670649846, 'n_estimators': 780, 'reg_alpha': 76, 'reg_lambda': 6}. Best is trial 0 with value: 0.4820435379044586.
[I 2026-04-08 21:06:50,187] Trial 1 finished with value: 0.5130635254026433 and parameters: {'max_depth': 7, 'min_child_weight': 5, 'subsample': 0.8245949475809506, 'colsample_bytree': 0.9022684041602722, 'learning_rate': 0.011607972174178147, 'n_estimators': 224, 'reg_alpha': 82, 'reg_lambda': 5}. Best is trial 0 with value: 0.4820435379044586.
[I 2026-04-08 21:06:59,777] Trial 2 finished with value: 0.48145144303815013 and parameters: {'max_depth': 8, 'min_child_weight': 9, 'subsample': 0.9775969471658247, 'colsample_bytree': 0.8077920552877865, 'learning_rate': 0.26832604160182966, 'n_estimators': 291, 'reg_alpha': 28, 'reg_lambda': 6}. Best is trial 2 with value: 0.48145144303815013.
[I 2026-04-08 21:07:10,421] Trial 3 finished with value: 0.48113837895444245 and parameters: {'max_depth': 3, 'min_child_weight': 13, 'subsample': 0.5413744369267408, 'colsample_bytree': 0.9191553084867895, 'learning_rate': 0.2313685612000277, 'n_estimators': 523, 'reg_alpha': 66, 'reg_lambda': 0}. Best is trial 3 with value: 0.48113837895444245.
[I 2026-04-08 21:07:15,789] Trial 4 finished with value: 0.48132716826950755 and parameters: {'max_depth': 5, 'min_child_weight': 11, 'subsample': 0.8132268060899479, 'colsample_bytree': 0.7331201211157623, 'learning_rate': 0.19480626254995778, 'n_estimators': 188, 'reg_alpha': 20, 'reg_lambda': 6}. Best is trial 3 with value: 0.48113837895444245.
[I 2026-04-08 21:07:52,890] Trial 5 finished with value: 0.48184410892026086 and parameters: {'max_depth': 7, 'min_child_weight': 6, 'subsample': 0.6189342954178092, 'colsample_bytree': 0.9531265556115259, 'learning_rate': 0.2650894931321473, 'n_estimators': 966, 'reg_alpha': 60, 'reg_lambda': 4}. Best is trial 3 with value: 0.48113837895444245.
[I 2026-04-08 21:08:03,707] Trial 6 finished with value: 0.48132589714119495 and parameters: {'max_depth': 3, 'min_child_weight': 10, 'subsample': 0.9515825926112852, 'colsample_bytree': 0.8176873251363259, 'learning_rate': 0.2252932842282132, 'n_estimators': 506, 'reg_alpha': 91, 'reg_lambda': 3}. Best is trial 3 with value: 0.48113837895444245.
[I 2026-04-08 21:08:12,427] Trial 7 finished with value: 0.4839683962847927 and parameters: {'max_depth': 9, 'min_child_weight': 6, 'subsample': 0.7669747269377181, 'colsample_bytree': 0.8688084477958652, 'learning_rate': 0.036751310890207015, 'n_estimators': 165, 'reg_alpha': 29, 'reg_lambda': 6}. Best is trial 3 with value: 0.48113837895444245.
[I 2026-04-08 21:08:25,672] Trial 8 finished with value: 0.48084175994983697 and parameters: {'max_depth': 4, 'min_child_weight': 10, 'subsample': 0.9258357013567343, 'colsample_bytree': 0.8451030048589148, 'learning_rate': 0.16760401070978848, 'n_estimators': 567, 'reg_alpha': 80, 'reg_lambda': 9}. Best is trial 8 with value: 0.48084175994983697.
[I 2026-04-08 21:08:45,158] Trial 9 finished with value: 0.4809344905221796 and parameters: {'max_depth': 4, 'min_child_weight': 18, 'subsample': 0.5308382559678131, 'colsample_bytree': 0.8950971468934533, 'learning_rate': 0.18607997711076554, 'n_estimators': 807, 'reg_alpha': 3, 'reg_lambda': 6}. Best is trial 8 with value: 0.48084175994983697.
[I 2026-04-08 21:08:56,648] Trial 10 finished with value: 0.4813461774887097 and parameters: {'max_depth': 5, 'min_child_weight': 1, 'subsample': 0.8951419639748965, 'colsample_bytree': 0.6681964135282124, 'learning_rate': 0.1117031109811525, 'n_estimators': 403, 'reg_alpha': 100, 'reg_lambda': 10}. Best is trial 8 with value: 0.48084175994983697.
[I 2026-04-08 21:09:13,907] Trial 11 finished with value: 0.4807375635402379 and parameters: {'max_depth': 4, 'min_child_weight': 20, 'subsample': 0.6711016011898768, 'colsample_bytree': 0.9945081902319891, 'learning_rate': 0.1519059575220272, 'n_estimators': 723, 'reg_alpha': 8, 'reg_lambda': 9}. Best is trial 11 with value: 0.4807375635402379.
[I 2026-04-08 21:09:34,559] Trial 12 finished with value: 0.48052642948244145 and parameters: {'max_depth': 5, 'min_child_weight': 14, 'subsample': 0.6757755256020468, 'colsample_bytree': 0.9594530789148379, 'learning_rate': 0.11409748463900696, 'n_estimators': 692, 'reg_alpha': 44, 'reg_lambda': 10}. Best is trial 12 with value: 0.48052642948244145.
[I 2026-04-08 21:09:56,933] Trial 13 finished with value: 0.4805387620672997 and parameters: {'max_depth': 5, 'min_child_weight': 20, 'subsample': 0.6687860674551348, 'colsample_bytree': 0.9980542433279388, 'learning_rate': 0.11511086233002371, 'n_estimators': 703, 'reg_alpha': 47, 'reg_lambda': 9}. Best is trial 12 with value: 0.48052642948244145.
[I 2026-04-08 21:10:30,746] Trial 14 finished with value: 0.48068368497555 and parameters: {'max_depth': 6, 'min_child_weight': 15, 'subsample': 0.6733278378060998, 'colsample_bytree': 0.9927103214976489, 'learning_rate': 0.09499910861066561, 'n_estimators': 938, 'reg_alpha': 46, 'reg_lambda': 8}. Best is trial 12 with value: 0.48052642948244145.
[I 2026-04-08 21:10:51,327] Trial 15 finished with value: 0.4807021328679193 and parameters: {'max_depth': 5, 'min_child_weight': 15, 'subsample': 0.6862603008794685, 'colsample_bytree': 0.7096736739702376, 'learning_rate': 0.11307643969303376, 'n_estimators': 657, 'reg_alpha': 44, 'reg_lambda': 10}. Best is trial 12 with value: 0.48052642948244145.
[I 2026-04-08 21:11:38,269] Trial 16 finished with value: 0.4807738332689981 and parameters: {'max_depth': 10, 'min_child_weight': 20, 'subsample': 0.5987069289178397, 'colsample_bytree': 0.5953800254206005, 'learning_rate': 0.07830508115513046, 'n_estimators': 854, 'reg_alpha': 56, 'reg_lambda': 8}. Best is trial 12 with value: 0.48052642948244145.
[I 2026-04-08 21:11:59,203] Trial 17 finished with value: 0.48067337412396743 and parameters: {'max_depth': 6, 'min_child_weight': 17, 'subsample': 0.7172509819537077, 'colsample_bytree': 0.9529029959301809, 'learning_rate': 0.1362602832868689, 'n_estimators': 624, 'reg_alpha': 38, 'reg_lambda': 8}. Best is trial 12 with value: 0.48052642948244145.
[I 2026-04-08 21:12:17,018] Trial 18 finished with value: 0.48057363272779263 and parameters: {'max_depth': 8, 'min_child_weight': 14, 'subsample': 0.6095858368674809, 'colsample_bytree': 0.9954619437136601, 'learning_rate': 0.07155357584147211, 'n_estimators': 417, 'reg_alpha': 34, 'reg_lambda': 2}. Best is trial 12 with value: 0.48052642948244145.
[I 2026-04-08 21:12:36,606] Trial 19 finished with value: 0.4805358006399659 and parameters: {'max_depth': 5, 'min_child_weight': 17, 'subsample': 0.8392738648540773, 'colsample_bytree': 0.7815426142149242, 'learning_rate': 0.12678137630389014, 'n_estimators': 674, 'reg_alpha': 16, 'reg_lambda': 10}. Best is trial 12 with value: 0.48052642948244145.
[I 2026-04-08 21:17:12,448] Trial 20 finished with value: 0.48137409649997126 and parameters: {'max_depth': 4, 'min_child_weight': 12, 'subsample': 0.863659859026932, 'colsample_bytree': 0.7749152200693217, 'learning_rate': 0.15576887999914152, 'n_estimators': 395, 'reg_alpha': 15, 'reg_lambda': 10}. Best is trial 12 with value: 0.48052642948244145.
[I 2026-04-08 21:25:42,821] Trial 21 finished with value: 0.480730243321538 and parameters: {'max_depth': 5, 'min_child_weight': 17, 'subsample': 0.7294228597662961, 'colsample_bytree': 0.6122304436647652, 'learning_rate': 0.1246547491872422, 'n_estimators': 687, 'reg_alpha': 52, 'reg_lambda': 9}. Best is trial 12 with value: 0.48052642948244145.
[I 2026-04-08 21:30:19,170] Trial 22 finished with value: 0.4803600212051725 and parameters: {'max_depth': 5, 'min_child_weight': 16, 'subsample': 0.8125527009260962, 'colsample_bytree': 0.9372839839541716, 'learning_rate': 0.08667632099829906, 'n_estimators': 742, 'reg_alpha': 19, 'reg_lambda': 8}. Best is trial 22 with value: 0.4803600212051725.
[I 2026-04-08 21:33:22,004] Trial 23 finished with value: 0.48030972276876005 and parameters: {'max_depth': 6, 'min_child_weight': 16, 'subsample': 0.8279388524755124, 'colsample_bytree': 0.9390579328351456, 'learning_rate': 0.07213464681362669, 'n_estimators': 901, 'reg_alpha': 18, 'reg_lambda': 7}. Best is trial 23 with value: 0.48030972276876005.
[I 2026-04-08 21:50:17,171] Trial 24 finished with value: 0.48054027524976106 and parameters: {'max_depth': 7, 'min_child_weight': 15, 'subsample': 0.8037510454058131, 'colsample_bytree': 0.9457111141950487, 'learning_rate': 0.0685666916019576, 'n_estimators': 853, 'reg_alpha': 25, 'reg_lambda': 7}. Best is trial 23 with value: 0.48030972276876005.
[I 2026-04-08 21:54:51,418] Trial 25 finished with value: 0.48071090098342123 and parameters: {'max_depth': 6, 'min_child_weight': 13, 'subsample': 0.8855704917889484, 'colsample_bytree': 0.868044407759645, 'learning_rate': 0.09119321165003516, 'n_estimators': 915, 'reg_alpha': 8, 'reg_lambda': 7}. Best is trial 23 with value: 0.48030972276876005.
[I 2026-04-08 21:55:16,035] Trial 26 finished with value: 0.4803877497099858 and parameters: {'max_depth': 8, 'min_child_weight': 16, 'subsample': 0.7707057223079602, 'colsample_bytree': 0.9346353225155276, 'learning_rate': 0.04979103603767204, 'n_estimators': 785, 'reg_alpha': 0, 'reg_lambda': 7}. Best is trial 23 with value: 0.48030972276876005.
[I 2026-04-08 21:55:41,177] Trial 27 finished with value: 0.4803510740107853 and parameters: {'max_depth': 8, 'min_child_weight': 16, 'subsample': 0.7840939581994517, 'colsample_bytree': 0.911182501927581, 'learning_rate': 0.04653786020448274, 'n_estimators': 780, 'reg_alpha': 3, 'reg_lambda': 7}. Best is trial 23 with value: 0.48030972276876005.
[I 2026-04-08 21:56:22,035] Trial 28 finished with value: 0.48084351976399975 and parameters: {'max_depth': 9, 'min_child_weight': 18, 'subsample': 0.8652135193031387, 'colsample_bytree': 0.8647011083035401, 'learning_rate': 0.010966642821422443, 'n_estimators': 990, 'reg_alpha': 12, 'reg_lambda': 4}. Best is trial 23 with value: 0.48030972276876005.
[I 2026-04-08 21:56:59,095] Trial 29 finished with value: 0.4806502946119561 and parameters: {'max_depth': 9, 'min_child_weight': 18, 'subsample': 0.7800753932591384, 'colsample_bytree': 0.5319514216467119, 'learning_rate': 0.0535799779151758, 'n_estimators': 869, 'reg_alpha': 21, 'reg_lambda': 5}. Best is trial 23 with value: 0.48030972276876005.
[I 2026-04-08 21:57:22,503] Trial 30 finished with value: 0.4805444763573353 and parameters: {'max_depth': 6, 'min_child_weight': 12, 'subsample': 0.7255284735477067, 'colsample_bytree': 0.8911084272030205, 'learning_rate': 0.032742226382205496, 'n_estimators': 767, 'reg_alpha': 7, 'reg_lambda': 7}. Best is trial 23 with value: 0.48030972276876005.
[I 2026-04-08 21:57:48,679] Trial 31 finished with value: 0.4805119236751681 and parameters: {'max_depth': 8, 'min_child_weight': 16, 'subsample': 0.7838318318166483, 'colsample_bytree': 0.9237316366799133, 'learning_rate': 0.05288502170515444, 'n_estimators': 765, 'reg_alpha': 0, 'reg_lambda': 7}. Best is trial 23 with value: 0.48030972276876005.
[I 2026-04-08 21:58:14,413] Trial 32 finished with value: 0.48043721772473014 and parameters: {'max_depth': 7, 'min_child_weight': 16, 'subsample': 0.7525847024380161, 'colsample_bytree': 0.9152421513580961, 'learning_rate': 0.045856238532553974, 'n_estimators': 804, 'reg_alpha': 1, 'reg_lambda': 8}. Best is trial 23 with value: 0.48030972276876005.
[I 2026-04-08 21:58:49,342] Trial 33 finished with value: 0.48038152204874723 and parameters: {'max_depth': 8, 'min_child_weight': 19, 'subsample': 0.8357912430395338, 'colsample_bytree': 0.828806046787133, 'learning_rate': 0.02545175325808846, 'n_estimators': 879, 'reg_alpha': 13, 'reg_lambda': 7}. Best is trial 23 with value: 0.48030972276876005.
[I 2026-04-08 21:59:32,906] Trial 34 finished with value: 0.4803850435904893 and parameters: {'max_depth': 10, 'min_child_weight': 19, 'subsample': 0.8442866339605954, 'colsample_bytree': 0.8351051682068497, 'learning_rate': 0.021133140643062626, 'n_estimators': 888, 'reg_alpha': 21, 'reg_lambda': 5}. Best is trial 23 with value: 0.48030972276876005.
[I 2026-04-08 22:00:06,413] Trial 35 finished with value: 0.4802862736730364 and parameters: {'max_depth': 7, 'min_child_weight': 8, 'subsample': 0.8063026110699525, 'colsample_bytree': 0.7994618984013965, 'learning_rate': 0.030529191485437156, 'n_estimators': 944, 'reg_alpha': 12, 'reg_lambda': 8}. Best is trial 35 with value: 0.4802862736730364.
[I 2026-04-08 22:00:41,478] Trial 36 finished with value: 0.4808631298880769 and parameters: {'max_depth': 7, 'min_child_weight': 8, 'subsample': 0.815599949811371, 'colsample_bytree': 0.7970451332353057, 'learning_rate': 0.09232967715384484, 'n_estimators': 951, 'reg_alpha': 33, 'reg_lambda': 8}. Best is trial 35 with value: 0.4802862736730364.
[I 2026-04-08 22:01:01,221] Trial 37 finished with value: 0.4803360844753028 and parameters: {'max_depth': 7, 'min_child_weight': 8, 'subsample': 0.9985515040953883, 'colsample_bytree': 0.7410610962819587, 'learning_rate': 0.06350546096145135, 'n_estimators': 602, 'reg_alpha': 24, 'reg_lambda': 6}. Best is trial 35 with value: 0.4802862736730364.
[I 2026-04-08 22:01:21,413] Trial 38 finished with value: 0.4803317032169947 and parameters: {'max_depth': 7, 'min_child_weight': 8, 'subsample': 0.9811797465338343, 'colsample_bytree': 0.7396106032188815, 'learning_rate': 0.06264148496712793, 'n_estimators': 575, 'reg_alpha': 27, 'reg_lambda': 6}. Best is trial 35 with value: 0.4802862736730364.
[I 2026-04-08 22:01:32,547] Trial 39 finished with value: 0.4813875804590688 and parameters: {'max_depth': 7, 'min_child_weight': 7, 'subsample': 0.9833969336083874, 'colsample_bytree': 0.7355352676670809, 'learning_rate': 0.059194628445581474, 'n_estimators': 308, 'reg_alpha': 68, 'reg_lambda': 4}. Best is trial 35 with value: 0.4802862736730364.
[I 2026-04-08 22:01:52,423] Trial 40 finished with value: 0.4803970691140485 and parameters: {'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.9493054315692065, 'colsample_bytree': 0.6905106798757709, 'learning_rate': 0.06684897833905323, 'n_estimators': 587, 'reg_alpha': 27, 'reg_lambda': 6}. Best is trial 35 with value: 0.4802862736730364.
[I 2026-04-08 22:02:08,278] Trial 41 finished with value: 0.4812710047961517 and parameters: {'max_depth': 6, 'min_child_weight': 9, 'subsample': 0.956716756308822, 'colsample_bytree': 0.750822852430868, 'learning_rate': 0.0437510937691241, 'n_estimators': 500, 'reg_alpha': 24, 'reg_lambda': 5}. Best is trial 35 with value: 0.4802862736730364.
[I 2026-04-08 22:02:30,233] Trial 42 finished with value: 0.4815751883444097 and parameters: {'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.9902025274018774, 'colsample_bytree': 0.6396168272138489, 'learning_rate': 0.03248443674906841, 'n_estimators': 606, 'reg_alpha': 32, 'reg_lambda': 6}. Best is trial 35 with value: 0.4802862736730364.
[I 2026-04-08 22:02:49,564] Trial 43 finished with value: 0.485083684821506 and parameters: {'max_depth': 8, 'min_child_weight': 8, 'subsample': 0.9282993023075603, 'colsample_bytree': 0.7643548064602692, 'learning_rate': 0.01589252121030673, 'n_estimators': 456, 'reg_alpha': 8, 'reg_lambda': 6}. Best is trial 35 with value: 0.4802862736730364.
[I 2026-04-08 22:03:13,731] Trial 44 finished with value: 0.48321743262801337 and parameters: {'max_depth': 9, 'min_child_weight': 6, 'subsample': 0.9173182589520159, 'colsample_bytree': 0.7056212407769435, 'learning_rate': 0.22313924982833722, 'n_estimators': 528, 'reg_alpha': 17, 'reg_lambda': 1}. Best is trial 35 with value: 0.4802862736730364.
[I 2026-04-08 22:03:19,903] Trial 45 finished with value: 0.4823049056544646 and parameters: {'max_depth': 8, 'min_child_weight': 11, 'subsample': 0.9990178132126758, 'colsample_bytree': 0.8076342774956795, 'learning_rate': 0.07896351470664799, 'n_estimators': 119, 'reg_alpha': 38, 'reg_lambda': 6}. Best is trial 35 with value: 0.4802862736730364.
[I 2026-04-08 22:03:45,991] Trial 46 finished with value: 0.480648736568947 and parameters: {'max_depth': 6, 'min_child_weight': 9, 'subsample': 0.960703334791331, 'colsample_bytree': 0.73304158961016, 'learning_rate': 0.10075555559786328, 'n_estimators': 825, 'reg_alpha': 5, 'reg_lambda': 5}. Best is trial 35 with value: 0.4802862736730364.
[I 2026-04-08 22:04:16,939] Trial 47 finished with value: 0.4804620798070636 and parameters: {'max_depth': 7, 'min_child_weight': 7, 'subsample': 0.911953109234549, 'colsample_bytree': 0.8498529479757208, 'learning_rate': 0.060801829770264534, 'n_estimators': 981, 'reg_alpha': 10, 'reg_lambda': 4}. Best is trial 35 with value: 0.4802862736730364.
[I 2026-04-08 22:04:53,564] Trial 48 finished with value: 0.4804055646921388 and parameters: {'max_depth': 8, 'min_child_weight': 10, 'subsample': 0.878034666431252, 'colsample_bytree': 0.6576404878705399, 'learning_rate': 0.043707646967177806, 'n_estimators': 915, 'reg_alpha': 24, 'reg_lambda': 7}. Best is trial 35 with value: 0.4802862736730364.
[I 2026-04-08 22:05:19,112] Trial 49 finished with value: 0.4807107728727936 and parameters: {'max_depth': 7, 'min_child_weight': 5, 'subsample': 0.504043477345949, 'colsample_bytree': 0.8836064346696514, 'learning_rate': 0.030231690513079806, 'n_estimators': 625, 'reg_alpha': 29, 'reg_lambda': 3}. Best is trial 35 with value: 0.4802862736730364.
[I 2026-04-08 22:05:30,898] Trial 50 finished with value: 0.4806209300607302 and parameters: {'max_depth': 6, 'min_child_weight': 8, 'subsample': 0.7927665033155565, 'colsample_bytree': 0.9702084399350044, 'learning_rate': 0.08084645924396744, 'n_estimators': 331, 'reg_alpha': 39, 'reg_lambda': 9}. Best is trial 35 with value: 0.4802862736730364.
[I 2026-04-08 22:05:58,372] Trial 51 finished with value: 0.4806922203979395 and parameters: {'max_depth': 7, 'min_child_weight': 7, 'subsample': 0.7507615596803285, 'colsample_bytree': 0.9711032779727357, 'learning_rate': 0.08476497366159758, 'n_estimators': 736, 'reg_alpha': 20, 'reg_lambda': 8}. Best is trial 35 with value: 0.4802862736730364.
[I 2026-04-08 22:06:11,966] Trial 52 finished with value: 0.48687717540684206 and parameters: {'max_depth': 3, 'min_child_weight': 9, 'subsample': 0.8160117127327491, 'colsample_bytree': 0.9109139331370113, 'learning_rate': 0.039858224734869836, 'n_estimators': 563, 'reg_alpha': 17, 'reg_lambda': 6}. Best is trial 35 with value: 0.4802862736730364.
[I 2026-04-08 22:06:43,103] Trial 53 finished with value: 0.48043164934281185 and parameters: {'max_depth': 6, 'min_child_weight': 14, 'subsample': 0.6451506961897402, 'colsample_bytree': 0.7158989410210785, 'learning_rate': 0.06658352937975938, 'n_estimators': 839, 'reg_alpha': 4, 'reg_lambda': 8}. Best is trial 35 with value: 0.4802862736730364.
[I 2026-04-08 22:07:13,957] Trial 54 finished with value: 0.48310070229896596 and parameters: {'max_depth': 6, 'min_child_weight': 12, 'subsample': 0.8580361086758089, 'colsample_bytree': 0.79169709708307, 'learning_rate': 0.29185784735283715, 'n_estimators': 923, 'reg_alpha': 12, 'reg_lambda': 9}. Best is trial 35 with value: 0.4802862736730364.
[I 2026-04-08 22:07:36,120] Trial 55 finished with value: 0.4805548491157371 and parameters: {'max_depth': 5, 'min_child_weight': 5, 'subsample': 0.7040557532605042, 'colsample_bytree': 0.6877783703809326, 'learning_rate': 0.1017795684964889, 'n_estimators': 733, 'reg_alpha': 19, 'reg_lambda': 7}. Best is trial 35 with value: 0.4802862736730364.

In [53]:
# import our feature engineered dataframe back to csv
df.to_csv("../data/nba_pbp_2020_2025_fe.csv")

In [54]:
# find the best parameters
study.best_params

{'max_depth': 6,
 'min_child_weight': 17,
 'subsample': 0.5643733174447721,
 'colsample_bytree': 0.9827635334946612,
 'learning_rate': 0.05072478407219559,
 'n_estimators': 771,
 'reg_alpha': 7,
 'reg_lambda': 10}

In [55]:
study.best_value

0.4801060553554118

In [57]:
%%time
# import the model we want to first use
from xgboost import XGBClassifier

# import the metrics we wanna use
from sklearn.metrics import log_loss, roc_auc_score, accuracy_score

# track the models we want to use on our data set
import mlflow

# start an mlflow run
with mlflow.start_run():
    
    # initialize the model and use the best parameters we got and unpack them using **
    model = XGBClassifier(**study.best_params)
    
    # train the model
    xg = model.fit(X_train, y_train)

    # log the parameters in this case the default ones
    mlflow.log_params(model.get_params())

    # log the model and give it a name
    model_info = mlflow.xgboost.log_model(xg, name = "best_params_xgboost_model")
    
    # get the model predicted values
    y_pred = model.predict(X_test)

    # get the probabilite values, so we can use for log loss and roc_auc
    y_proba = model.predict_proba(X_test)

    # get the models metrics
    score = accuracy_score(y_test, y_pred)
    ll = log_loss(y_test, y_proba[:, 1])
    roc_auc = roc_auc_score(y_test, y_proba[:, 1])

    # log the metrics
    mlflow.log_metrics({"log_loss": ll, "accuracy_score": score, "roc_auc": roc_auc})

CPU times: user 1min 52s, sys: 2.73 s, total: 1min 55s
Wall time: 25 s